Repository redhat-plumbers/systemd-rhel7, pull requests merged in 2020-03, with the labels that each got.

#83 (#1807796) journal: do not trigger assertion when journal_file_close() get NULL
  src/journal/journal-file.c
  src/journal/journald-server.c
Labels: rhel-7.7

#82 (#1807798) journal: do not trigger assertion when journal_file_close() get NULL
  src/journal/journal-file.c
  src/journal/journald-server.c
Labels: rhel-7.8

#86 (#1809159) Bz1809159
  src/core/mount.c
Labels: rhel-7.8

#87 (#1810576) rework StopWhenUnneeded= logic
  src/core/manager.c
  src/core/manager.h
  src/core/unit.c
  src/core/unit.h
Labels: rhel-7.8

#91 (#1809159) fix the fix for #1691511
  src/core/mount.c
Labels: rhel-7.8

#97 (#1817504) sd-bus: when attached to an sd-event loop, disconnect on processing errors
  src/libsystemd/sd-bus/sd-bus.c
Labels: rhel-7.8

#96 (#1817503) sd-bus: when attached to an sd-event loop, disconnect on processing errors
  src/libsystemd/sd-bus/sd-bus.c
Labels: ci-waived, rhel-7.7
