Repository redhat-plumbers/systemd-rhel7, pull requests merged in 2020-10, with the labels that each got.

#123 (#1793527) Avoid needless PropertiesChanged notifications (follow-ups)
  src/core/unit.c
Labels: rhel-7.9

#125 (#1889314) core: fix unnecessary fallback to the rescue mode caused by initrd-sw…
  src/core/service.c
  src/shared/special.h
Labels: rhel-7.6

#124 (#1889315) core: fix unnecessary fallback to the rescue mode caused by initrd-sw…
  src/core/service.c
  src/shared/special.h
Labels: rhel-7.7
